version: "3"
services:
  nginx:
      build: .
      image: nginx-reverse-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes: 
        - "./conf:/etc/nginx/conf.d"
      network_mode: "host" 